apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    editable: true
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: compliance_db
    user: compliance
    secureJsonData:
      password: compliance123
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
    uid: postgres
    editable: true